version: '3.8'

services:
  php-apache:
    image: php:7.4-apache
    volumes:
      - ./Aplicatiuweb:/var/www/html
    ports:
      - "8003:80"

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - "./database:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: projectx
      MYSQL_USER: alumne
      MYSQL_PASSWORD: alumne1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app
    